# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseware',
            old_name='teacher',
            new_name='subject',
        ),
    ]
