# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20160407_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseware',
            name='number',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
